apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartgpu-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartgpu-frontend
  template:
    metadata:
      labels:
        app: smartgpu-frontend
    spec:
      containers:
        - name: smartgpu-frontend
          image: smartgpu-frontend:latest
          ports:
            - containerPort: 5173
